spring.application.name=ms-consulta
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/hospitaldb
spring.datasource.username=hospital
spring.datasource.password=hospital123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

ms.turnos.url=http://localhost:8081